export const config = {
  BACKEND_ENDPOINT: process.env.NEXT_PUBLIC_BACKEND_ENDPOINT,
  PROD_BACKEND_ENDPOINT: process.env.NEXT_PUBLIC_PROD_BACKEND_ENDPOINT,
  RAZORPAY_ID: process.env.NEXT_PUBLIC_RAZORPAY_ID,
  RAZORPAY_SECRET: process.env.NEXT_PUBLIC_RAZORPAY_SECRET,
  EMAILJS_SERVICE_ID: process.env.NEXT_PUBLIC_EMAILJS_SERVICE_ID,
  EMAILJS_TEMPLATE_ID: process.env.NEXT_PUBLIC_EMAILJS_TEMPLATE_ID,
  EMAILJS_PUBLIC_KEY: process.env.NEXT_PUBLIC_EMAILJS_PUBLIC_KEY,
  RESEND_API_KEY: process.env.NEXT_PUBLIC_RESEND_API_KEY,
};
